server:
  port: 8205

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/jpa_exam?characterEncoding=utf8&useSSL=false&useUnicode=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: kjfoeksdkfj
    hikari:
      minimum-idle: 5
      connection-test-query: SELECT 1 FROM DUAL
      maximum-pool-size: 20
      auto-commit: true
      idle-timeout: 30000
      pool-name: blogHikariCP
      max-lifetime: 60000
      connection-timeout: 30000

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        temp:
          use_jdbc_metadata_defaults: false
    open-in-view: true
logging:
  level:
    org.hibernate.type.descriptor.sql.BasicBinder: debug
